### PR TITLE
UPDATE THIS TO HAVE THE RIGHT TITLE PLEASE

### PR DESCRIPTION
**Pull request by ArminNouri98**
## Learners, PR Template

Self checklist

- [x] I have committed my files one by one, on purpose, and for a reason
- [x] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [x] I have tested my changes
- [x] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [x] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

### CODE REVIEW

**Review by ArminNouri98 — COMMENTED** [review]
form page

**Review by ArminNouri98 — COMMENTED** [review]
> > ### <span aria-hidden="true">✅</span> Deploy Preview for *cyf-ufd* ready!
> > 
> > 
> > |  Name | Link |
> > |:-:|------------------------|
> > |<span aria-hidden="true">🔨</span> Latest commit | b69cfe1b808ed9b8b41a300ae36cc6a6d7440afe |
> > |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/cyf-ufd/deploys/670a7793f5598e0008baabcd |
> > |<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-197--cyf-ufd.netlify.app](https://amodule-user-focused-dat-armin-nouri.netlify.app/) |
> > |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
> > ---
> > 
> > _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/cyf-ufd/configuration/notifications#deploy-webhooks)._ 
> 
>

**Comment by ArminNouri98** [comment]
> > ### <span aria-hidden="true">✅</span> Deploy Preview for *cyf-ufd* ready!
> > 
> > 
> > |  Name | Link |
> > |:-:|------------------------|
> > |<span aria-hidden="true">🔨</span> Latest commit | b69cfe1b808ed9b8b41a300ae36cc6a6d7440afe |
> > |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/cyf-ufd/deploys/670a7793f5598e0008baabcd |
> > |<span aria-hidden="true">😎</span> Deploy Preview | [https://amodule-user-focused-dat-armin-nouri.netlify.app) |
> > |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
> > ---
> > 
> > _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/cyf-ufd/configuration/notifications#deploy-webhooks)._ 
> 
>

**Review by ArminNouri98 — COMMENTED** [review]
> ### <span aria-hidden="true">✅</span> Deploy Preview for *cyf-ufd* ready!
> 
> 
> |  Name | Link |
> |:-:|------------------------|
> |<span aria-hidden="true">🔨</span> Latest commit | b69cfe1b808ed9b8b41a300ae36cc6a6d7440afe |
> |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/cyf-ufd/deploys/670a7793f5598e0008baabcd |
> |<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-197--cyf-ufd.netlify.app](https://amodule-user-focused-dat-armin-nouri.netlify.app/) |
> |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
> ---
> 
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/cyf-ufd/configuration/notifications#deploy-webhooks)._

**Review by ArminNouri98 — COMMENTED** [review]
> > ### <span aria-hidden="true">✅</span> Deploy Preview for *cyf-ufd* ready!
> > 
> > 
> > |  Name | Link |
> > |:-:|------------------------|
> > |<span aria-hidden="true">🔨</span> Latest commit | b69cfe1b808ed9b8b41a300ae36cc6a6d7440afe |
> > |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/cyf-ufd/deploys/670a7793f5598e0008baabcd |
> > |<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-197--cyf-ufd.netlify.app](https://amodule-user-focused-dat-armin-nouri.netlify.app/) |
> > |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
> > ---
> > 
> > _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/cyf-ufd/configuration/notifications#deploy-webhooks)._ 
> 
>

**Review by SallyMcGrath — COMMENTED** [review]
Thanks for this! I don't think it is related to the coursework assignment. Do you need help finding the assignment and working through it? 

Come to a study group and work on this assignment with a mentor or other learners who can help you. ❤️

**Pull request closed without merging**
