### PR TITLE
Feature/wireframe review

### PR DESCRIPTION
**Pull request by StanStarishko**
# StanStarishko | Stanislav Starishko | Module-User-Focused-Data | Week 1

## Learners, PR Template

Self checklist

- [✅] I have committed my files one by one, on purpose, and for a reason
- [✅] I have titled my PR with StanStarishko | Stanislav Starishko | Module-User-Focused-Data | Week 1
- [✅ I have tested my changes
- [✅] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [✅] My changes meet the [requirements](./README.md) of this task

## Changelist

I created a website according to the provided template. The source code is in the Wireframe folder. I added an **index.html** file to the root directory so that I could deploy it to [**netlify**](https://stanislav-about-git.netlify.app/)

## Questions

No questions. Thanks in advance for your review.

### CODE REVIEW

**Review by shieldo — CHANGES_REQUESTED** [review]
Thanks for this pull request @StanStarishko !

Copying in the acceptance criteria for this task:


The webpage has a consistent color scheme for links and text.
PASSED

Semantic HTML tags are used to structure the webpage.
PASSED - there is really good use of semantic HTML elements here.

The page header includes a title and description.
PASSED

The articles section has three articles, each including a title, summary, and a link.
PASSED

The page footer is fixed to the bottom of the viewport.
PASSED

The first article is styled using the :first-child pseudo-class.
- This pseudo-class doesn't exist in the style sheet currently. Would you like some assistance with understanding what a pseudo-class is in CSS?

The webpage is styled using a linked .css file.
PASSED

The webpage is properly committed and pushed to a branch on GitHub.
I would have a look here at the commits in the branch - good git commits each have a clear and "atomic" purpose. There can be multiple commits in one feature branch, but each change should have a clear purpose, and should not just be a save point for where you have got to in a piece of work. I would have a look at rebasing this branch and squashing commits down into individual meaningful changes.

The webpage does not use any frameworks such as Bootstrap.
PASSED

---------

This is a really good piece of work! I have a couple of pieces of feedback that I would like you to look at. Also please feel free to ask any further questions about anything you weren't too sure about - the purpose of these pull requests is to start a discussion about anything you aren't too clear about.

**Comment by StanStarishko** [comment]
Thanks for this _**review requirements**_ @shieldo 

> Thanks for this pull request @StanStarishko !
> 
> Copying in the acceptance criteria for this task:
>
>  ...
> 
> The first article is styled using the :first-child pseudo-class.
> 
> * This pseudo-class doesn't exist in the style sheet currently. Would you like some assistance with understanding what a pseudo-class is in CSS?
> 

Yes, indeed, this pseudo-class is missing from my code. But I understand what it is and how it can be used.

### First, I would like to explain how it works, perhaps I understand something incorrectly.

So, This pseudo-class is used only in the style design code (in my case, it is `css/style.css`). It selects the first element among all children of the parent container. For example, if there are several elements inside the `<div>`, the pseudo-class `first-child `will be applied only to the first of them.

#### Example:

#### html:
```
<div>
  <p>First paragraph</p>
  <p>Second paragraph</p>
  <p>Third paragraph</p>
</div>
```

#### css:
```
div p:first-child {
  color: red;
}
```
In this example, only the first paragraph inside the `<div>` will be red

### Why is this not in my code?
- Frankly, when I was doing this task, I forgot about this requirement
- But, I automatically design structures and algorithms in a completely different way on the subconscious. I have more than 30 years of experience in this. I hope this and understanding how it works will help me get a PASS in this task. The structure of my HTML document, in my opinion, does not allow me to use this pseudo-class. But if in another document I have a situation similar to the example, I will, of course, be able to use this pseudo-class without assigning a class to the "first child" in the HTML document, since it already exists by default

> ...
> 
> The webpage is properly committed and pushed to a branch on GitHub. I would have a look here at the commits in the branch - good git commits each have a clear and "atomic" purpose. There can be multiple commits in one feature branch, but each change should have a clear purpose, and should not just be a save point for where you have got to in a piece of work. 
> 
> ...
> 

It may be hard to believe, but the principles and approaches of **TDD** (Test-Driven Development) are also in my subconscious when I write code even in a language that is very familiar to me, and even more so when I practice in new technologies for me. That's why I test every line of my code, sometimes I can write a small block in CSS that I am confident in, but I still test very often. That's why all my `"test"` and `"testing"` commits fully meet the goals and objectives that I had set for myself. Why was this often, until the last "Beta version" commit? Because I was developing on a remote repository from my laptop, without figuring out how to properly clone it to my local repository. When I realized that I was wasting a lot of time committing and visualizing changes in the code, I made a copy to my local computer, quickly finished the code and uploaded the final result in the `"Beta version"` commit. And also additional files, so that my whole "assembly" works. At the moment I have already figured out how to clone the repository to the local computer and even the preview started working for me, which did not work on the remote repository. So I hope that in the next project there will not be so many seemingly "chaotic" commits. Thank you for paying attention to this. This also caused me discomfort, but I am just learning to work with GIT. Before this, I used another version control product. It is much simpler than GIT.

## Questions

> ...
>
> I would have a look at rebasing this branch and squashing commits down into individual meaningful changes.
>
>...

I would be happy if you could give me a direction on how to fix this. Could you give some specific advice or links where I can read about this and so that there would be as little "water" as possible (unnecessary information about nothing, as is often the case in Internet materials)

**Comment by shieldo** [comment]
Thanks for this feedback, @StanStarishko ! It's clear that you understand the exercise well, including the `first-child` pseudo-class. This submission already fulfils the criteria for the course, so don't worry about that.

I understand about why there are a number of small commits here - pushing individual commits to trigger a deployment upstream (in this case to Netlify) is something I've definitely often done :) and it's great that you are circumspect about the individual changes that you make and how to verify that they are good.

On the subject of git, one of the best resources I've read is the book 'Pro Git' by Scott Chacon, who was one of the founders of GitHub. [The book is available to read on the web](https://git-scm.com/book/en/v2) on the git website! I'd recommend looking at [the chapter on rewriting history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), especially the section on interactive rebases. I'm not sure which version control system you are used to and whether it is centralised or distributed, but an important thing about git is that it is distributed, meaning that each repository is a full copy whether on your local machine or within a platform such as GitHub - this makes it a bit more complex to work with compared to centralised systems, but a lot more powerful. This book definitely isn't the "water" you are describing (I can definitely agree about internet resources sometimes being quite fluffy), and you'll see on the site it's even available in Ukrainian!

So I hope that's a useful resource for you. You don't need to change the commits here, but might like to do that as an exercise to help your understanding of git. (Hint: if you do a `git push` with the additional option `--force-with-lease`, it'll allow you to update any commits that you have made in a remote feature branch, but will not allow you to overwrite other people's commits, which is usually what you want!) (Or if it's a repository that you own and only you can commit to, worrying about other people isn't a problem! As ever, it's about context.)

Thanks again for your work here.

**Comment by StanStarishko** [comment]
Oh, thanks @shieldo ,

For such a detailed and clear answer. This is very valuable to me, especially thanks for the great source of information about Git. I am very happy that there is a translation of this book into my native language, which will make it easier to understand the material when I cannot understand or translate from English purely.

I will definitely try to optimize the number of commits in this branch in my free time, maybe even after completing the course. This is now my optional task number one. 👍

I am very grateful to you for such a useful and valuable answer

**Pull request closed without merging**
